global:
    checkNewVersion: true
    sendAnonymousUsage: false

entryPoints:
    web:
        address: ":80"

    mysql:
        address: ":3306"

api:
    dashboard: true
    insecure: true

providers:
    docker: 
        endpoint: "unix:///var/run/docker.sock"
        watch: true
    file:
        directory: /configs
        watch: true
